language: javascript
sudo: required

before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start

before_script:
  - npm install -g karma
  - npm install -g requirejs
  - npm install -g jasmine-core karma-jasmine
  - npm install -g karma-requirejs
  - npm install -g karma-chrome-launcher
  - npm install -g karma-browserstack-launcher

script:
  - karma start karma.conf.js --single-run

notifications:
  slack: lacnic-eng:jSDKPP0pyOgA5JV4lsQTGtuP
