language: javascript
sudo: required

services:
  - xvfb

before_install:
    - export DISPLAY=:99.0

before_script:
  - npm install -g karma
  - npm install -g requirejs
  - npm install -g jasmine-core karma-jasmine
  - npm install -g karma-requirejs
  - npm install -g karma-chrome-launcher
  - npm install -g karma-browserstack-launcher

script:
  - karma start karma.conf.js --single-run

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: "build/webmeasurements.js"
  on:
    branch: release
