language: node_js
os: linux
dist: xenial

services:
  - xvfb

before_install:
    - export DISPLAY=:99.0

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: "build/webmeasurements.js"
  on:
    branch: release
